app_port : 9000
client_url : http://localhost:4200
jwt:
  audience : test
  issuer : test
  secret_key : L[S18I}'J&2>&YC(b%~*kOnFvLHv+]vI-sv%!1gpY}8GZ0]NMY%HJMh@vAEjy;Q 
database:
  username : admin
  password : root
  host : localhost
  port : 5432 
  database_name : brackets_db