import QueryProvider from 'client/providers/QueryProvider';
import './global.css';
import { Toaster } from 'react-hot-toast';
import AuthContext from 'client/providers/AuthContext';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <QueryProvider>
          <AuthContext>
            {children}
          </AuthContext>
        </QueryProvider>
      </body>
    </html>
  );
}
