app:
  host: 0.0.0.0
  port : 8000 
  client_url : http://localhost:3000
jwt:
  issuer: test
  audience : test
  secret_key : secret
database:
    username : username
    password: password
    host : host
    port : 1234
    database_name : db
    require_ssl: false