import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./Markdown.css"
import AuthContext from "@/providers/AuthContext";
import QueryProvider from "@/providers/QueryProvider";
import { Toaster } from "react-hot-toast";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
        <QueryProvider>
          <ReactQueryDevtools />
          <AuthContext>
            {children}
          </AuthContext>
        </QueryProvider>
      </body>
    </html>
  );
}
