import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";

import { cn } from "@/lib/utils"
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/providers/QueryProvider";
import AuthContext from "@/providers/AuthContext";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Toaster />
        <QueryProvider>
          <AuthContext>
            {children}
          </AuthContext>
        </QueryProvider>
      </body>
    </html>
  );
}
