version: '3.4'

services:
  appdb:
    image: postgres
 
  pgadmin:
    image: dpage/pgadmin4

  # blog.api:
  #   image: ${DOCKER_REGISTRY-}blog-api
  #   build:
  #     context: .
  #     dockerfile: server/Blog.API/Dockerfile

      
volumes:
  appdb-data:
  redis-db-data: