version: '3.4'

services:
  db:
    container_name: db 
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5 

  pgadmin:
    restart: always
    container_name: pgadmin
    ports:
      - ${PGA_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD} 
  