version: '3.4'

services:
  appdb:
    container_name: appdb
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - appdb-data:/var/lib/postgresql/data

  pgadmin:
    restart: always
    container_name: pgadmin
    ports:
      - ${PGA_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL} 
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD} 
  
  # blog.api:
  #   container_name: blog.api
  #   depends_on:
  #     - appdb
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - "ConnectionStrings:DB=Host=${DB_HOST}:${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
  #   ports:
  #     - "8000:3000"
